name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: github-pages
    steps:
      - name: 🔧 Checkout source code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: 🔧 Install dependencies
        run: npm install

      - name: 📤 Build and Deploy
        run: npm run deploy